### ISSUE TITLE
GL渲染内存泄漏

### ISSUE THREAD

**Issue by lcings** [o0olele/OpenGL_OpenCV_AR#2]
程序运行一段时间内存爆掉，跟踪内存可知：
background.cpp中void Background::Draw(Mat &frame)
backmesh.h中void Draw(cv::Mat &frame)
渲染每一帧用glGenTextures(1, &texture);重复创建新的纹理ID，
解决办法：函数尾部加glDeleteTextures(1, &texture);

**Comment by o0olele** [comment]
了解了，谢谢大佬
